#!/bin/sh /etc/rc.common
#

START=25
USE_PROCD=1

PROG="/usr/bin/goeap_proxy"

boot()
{
    ubus -t 30 wait_for network.device
    rc_procd start_service
}

start_service()
{
    config_load goeap_proxy
    config_get wan proxy wan
    config_get router proxy router

    procd_open_instance
    procd_set_param respawn ${respawn_threshold:-2} ${respawn_timeout:-30} ${respawn_retry:-0}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param command $PROG --syslog
    procd_set_param file /etc/config/goeap_proxy
    procd_append_param command -if-wan "${wan}"
    procd_append_param command -if-router "${router}"
    procd_close_instance
}

service_triggers()
{
    procd_add_reload_trigger "goeap_proxy"
}

